# Generated by Django 6.0.3 on 2026-03-19 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisite', '0002_blogcomment_blogcommentreaction_blogpostview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_token', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='safarisite.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'channel', 'created_at'], name='safarisite__post_id_86990a_idx')],
            },
        ),
    ]
