# Generated by Django 6.0.3 on 2026-03-19 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarisite', '0003_blogpostshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('fire', '🔥'), ('laugh', '😂')], max_length=20),
        ),
        migrations.CreateModel(
            name='BlogPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_token', models.CharField(max_length=120)),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('wow', '🔥'), ('laugh', '😂')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='safarisite.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'actor_token'), name='unique_post_reactor')],
            },
        ),
    ]
